### PR TITLE
linter&tests fixes

### LINKED ISSUE #22: Golangci-lint errors
I suggest running [golangci-lint](https://github.com/golangci/golangci-lint) and addressing the issues it reports. There are currently cases of:
- errors not checked
- empty branches
- type check errors
- and others

Would be good to also setup a CI enforcing the checks.

### LINKED ISSUE #37: Fix unit tests and lint failures
As of #33 the CI will now run unit tests and lints on the codebase. It seems that currently a lot of the tests are broken and code needs to be updated to pass lint checks.

After these are fixed, the CI steps should be marked as required for merging pull requests.

### PR DESCRIPTION
**Pull request by matevz**
Fixes https://github.com/starfishlabs/oasis-evm-web3-gateway/issues/37

### CODE REVIEW

File: indexer/backend.go [hunk 1]
```diff
@@ -200,8 +202,22 @@ func (p *psqlBackend) Index(
...
 		}
-		p.storage.Store(txRef)
-		p.storage.Store(ethTx)
+		if err = p.storage.Store(txRef); err != nil {
+			p.logger.Error("failed to store transaction reference",
+				"err", err,
+				"round", round,
+				"index", idx,
+			)
+			continue
```
Comment (kostko) [inline indexer/backend.go]: I'm not sure that continuing here is ok as this indicates some problem with the underlying storage? We should just return an error, also below.

File: indexer/backend.go [hunk 2]
```diff
@@ -245,7 +261,7 @@ func (p *psqlBackend) QueryBlockHash(round uint64) (ethcommon.Hash, error) {
 	}
 
 	if err != nil {
-		p.logger.Error("indexer error", "err", err)
+		p.logger.Error("indexer error: query block hash", "err", err)
```
Comment (kostko) [inline indexer/backend.go]:
```suggestion
		p.logger.Error("failed to query block hash", "err", err)
```

File: indexer/backend.go [hunk 3]
```diff
@@ -258,7 +274,9 @@ func (p *psqlBackend) storeIndexedRound(round uint64) {
 		Round: round,
 	}
 
-	p.storage.Update(r)
+	if err := p.storage.Update(r); err != nil {
+		p.logger.Error("indexer error: store indexed round", "err", err)
```
Comment (kostko) [inline indexer/backend.go]:
```suggestion
		p.logger.Error("failed to store indexed round", "err", err)
```

File: indexer/backend.go [hunk 4]
```diff
@@ -258,7 +274,9 @@ func (p *psqlBackend) storeIndexedRound(round uint64) {
...
+	}
```
Comment (kostko) [inline indexer/backend.go]: Should this be changed to propagate errors instead of just logging them?

File: main.go [hunk 5]
```diff
@@ -41,73 +41,78 @@ func init() {
 }
 
 func main() {
-	rootCmd.Execute()
+	if err := rootCmd.Execute(); err != nil {
+		fmt.Fprintf(os.Stderr, "ERROR: Command failed: %v\n", err)
```
Comment (kostko) [inline main.go]: Could use `cobra.CheckErr(err)`.

File: main.go [hunk 6]
```diff
@@ -41,73 +41,78 @@ func init() {
...
+	}
 }
 
-func runRoot(cmd *cobra.Command, args []string) {
+func runRoot(cmd *cobra.Command, args []string) error {
 	// Initialize logging.
 	if err := logging.Initialize(os.Stdout, logging.FmtLogfmt, logging.LevelDebug, nil); err != nil {
 		fmt.Fprintf(os.Stderr, "ERROR: Unable to initialize logging: %v\n", err)
-		os.Exit(1)
+		return err
```
Comment (kostko) [inline main.go]: This is not the best as it will also print usage.

File: rpc/eth/api.go [hunk 7]
```diff
@@ -241,8 +235,8 @@ func (api *PublicAPI) GetBalance(address common.Address, blockNum ethrpc.BlockNu
 	return (*hexutil.Big)(res.ToBigInt()), nil
 }
 
-// ChainId return the EIP-155  chain id for the current network
-func (api *PublicAPI) ChainId() (*hexutil.Big, error) {
+// ChainID return the EIP-155  chain id for the current network.
```
Comment (ptrus) [inline rpc/eth/api.go]:
```suggestion
// ChainID return the EIP-155 chain id for the current network.
````

File: rpc/eth/api.go [hunk 8]
```diff
@@ -648,33 +644,45 @@ func (api *PublicAPI) GetTransactionReceipt(txHash common.Hash) (map[string]inte
...
-		startRoundInclusive = round
-		endRoundInclusive = round
-	} else {
-		if filter.FromBlock != nil {
-			round, err := api.roundParamFromBlockNum(ethrpc.BlockNumber(filter.FromBlock.Int64()))
-			if err != nil {
-				return nil, fmt.Errorf("convert from block number to round: %w", err)
-			}
-			startRoundInclusive = round
+		start = round
```
Comment (ptrus) [inline rpc/eth/api.go]:
```suggestion
		return round, round, nil
```

And move start/end declarations bellow to line 661.

File: tests/rpc/rpc_test.go [hunk 9]
```diff
@@ -16,24 +17,25 @@ import (
...
-)
-
-// The dave private key derive from the seed "oasis-runtime-sdk/test-keys: dave"
+// The dave private key derive from the seed "oasis-runtime-sdk/test-keys: dave".
+// TODO: Can we use Oasis Alice.Signer.ContextSign() directly?
 var daveKey, _ = crypto.HexToECDSA("c0e43d8755f201b715fd5a9ce0034c568442543ae0a0ee1aec2985ffe40edb99")
 
 func TestMain(m *testing.M) {
-	HOST = "http://localhost:8545"
+	if err := Setup(); err != nil {
```
Comment (ptrus) [inline tests/rpc/rpc_test.go]: Lets add a check here (in `TestMain`) that checks if PostgreSQL is running on the configured address/port, and in case it's not, print a nice error that instructs the user to run it.

This will help anyone trying to run these tests locally.

Could also include the following helper in the error message: 
```
docker run --rm --name postgress -e POSTGRES_PASSWORD=postgres  -p 5432:5432 postgres:13.3-alpine
```
as an example of how to run it :-)

---

Could also check that oasis-node socket is available at the provided address, and instruct the user to run the `tests/tools/spinup-oasis-stack.sh` in case it's not.

File: indexer/backend.go (hunk 1 above)
Comment (matevz) [reply indexer/backend.go]: refactored.

File: indexer/backend.go (hunk 3 above)
Comment (matevz) [reply indexer/backend.go]: refactored.

File: conf/config.go [hunk 10]
```diff
@@ -125,7 +158,7 @@ type GatewayHTTPConfig struct {
 
 	// Timeouts allows for customization of the timeout values used by the HTTP RPC
 	// interface.
-	Timeouts *HTTPTimeouts `mapsstructure:"timeouts"`
+	Timeouts *HTTPTimeouts `mapstructure:"timeouts"`
```
Comment (kostko) [inline conf/config.go]: Should the tag actually be `koanf` as above?

File: conf/config.go [hunk 11]
```diff
@@ -53,6 +54,38 @@ func (cfg *Config) Validate() error {
 	return nil
 }
 
+// InitLogging initializes logging based on the provided configuration.
+func (cfg *Config) InitLogging() error {
```
Comment (kostko) [inline conf/config.go]: It would be better to have this in some logging package and pass `cfg *Config` as argument.

File: indexer/utils.go [hunk 12]
```diff
@@ -238,7 +239,10 @@ func (p *psqlBackend) StoreBlockData(oasisBlock *block.Block, txResults []*clien
 		logs = Logs2EthLogs(oasisLogs, blockNum, bhash, ethTx.Hash(), uint32(txIndex))
 		// store logs
 		dbLogs := eth2DbLogs(logs)
-		p.storage.Store(dbLogs)
+		if err = p.storage.Store(dbLogs); err != nil {
+			p.logger.Error("Failed to store logs", "height", blockNum, "index", txIndex, "logs", oasisLogs, "error", err.Error())
```
Comment (kostko) [inline indexer/utils.go]:
```suggestion
			p.logger.Error("Failed to store logs", "height", blockNum, "index", txIndex, "logs", oasisLogs, "err", err.Error())
```

File: model/init.go [hunk 13]
```diff
@@ -5,20 +5,29 @@ import (
 	"github.com/go-pg/pg/v10/orm"
 )
 
+func getModels() []interface{} {
+	m := make([]interface{}, 0)
+	return append(m, new(AccessTuple), new(Block), new(BlockRef), new(Header), new(TransactionRef), new(Transaction), new(IndexedRoundWithTip), new(Log), new(Receipt))
```
Comment (kostko) [inline model/init.go]: Break this into multiple lines. Also why are you using `append` instead of just creating a slice?

File: rpc/eth/api.go [hunk 14]
```diff
@@ -86,11 +86,11 @@ func (api *PublicAPI) roundParamFromBlockNum(blockNum ethrpc.BlockNumber) (uint6
 		var earliest uint64
 		clrBlk, err := api.client.GetLastRetainedBlock(api.ctx)
 		if err != nil {
-			api.Logger.Error("failed to get last retained block from client", "error", err)
+			return 0, fmt.Errorf("failed to get last retained block from client: %v", err)
```
Comment (kostko) [inline rpc/eth/api.go]:
```suggestion
			return 0, fmt.Errorf("failed to get last retained block from client: %w", err)
```

File: rpc/eth/api.go [hunk 15]
```diff
@@ -86,11 +86,11 @@ func (api *PublicAPI) roundParamFromBlockNum(blockNum ethrpc.BlockNumber) (uint6
...
 		}
 		ilrRound, err := api.backend.QueryLastRetainedRound()
 		if err != nil {
-			api.Logger.Error("failed to get last retained block from indexer", "error", err)
+			return 0, fmt.Errorf("failed to get last retained block from indexer: %v", err)
```
Comment (kostko) [inline rpc/eth/api.go]:
```suggestion
			return 0, fmt.Errorf("failed to get last retained block from indexer: %w", err)
```

File: rpc/eth/api.go [hunk 16]
```diff
@@ -332,7 +333,7 @@ func (api *PublicAPI) Call(args utils.TransactionArgs, blockNum ethrpc.BlockNumb
 	if err != nil {
 		if strings.HasPrefix(err.Error(), revertErrorPrefix) {
 			revertErr := api.NewRevertError(err)
-			api.Logger.Error("failed to execute SimulateCall, reverted", "error", err, "reason", revertErr.reason)
+			api.Logger.Error("failed to execute SimulateCall, reverted", "error", err, "reason", revertErr.Reason)
```
Comment (kostko) [inline rpc/eth/api.go]: (Also elsewhere, to be consistent with what we use in Oasis Core et al.)
```suggestion
			api.Logger.Error("failed to execute SimulateCall, reverted", "err", err, "reason", revertErr.Reason)
```

File: rpc/eth/api_test.go [hunk 17]
```diff
@@ -12,7 +12,7 @@ func TestRejectOverlong(t *testing.T) {
 	var b hexutil.Big
 	err := json.Unmarshal([]byte("\"0xf1111111122222222333333334444444455555555666666667777777788888888\""), &b)
 	if err != nil {
-		fmt.Printf("overlong unamrshal failed (expected): %v\n", err)
+		fmt.Printf("overlong unmarshal failed (expected): %v\n", err)
```
Comment (kostko) [inline rpc/eth/api_test.go]: Should this use `t.Logf` instead?

File: server/server_test.go [hunk 18]
```diff
@@ -2,75 +2,35 @@ package server
...
-	}
-	return server
-}
-
-func doHTTPRequest(t *testing.T, req *http.Request) *http.Response {
-	client := http.DefaultClient
-	resp, err := client.Do(req)
-	if err != nil {
-		t.Fatalf("could not issue a GET request to the given endpoint: %v", err)
+		return nil, fmt.Errorf("could not create a new web3 gateway: %v", err)
```
Comment (kostko) [inline server/server_test.go]:
```suggestion
		return nil, fmt.Errorf("could not create a new web3 gateway: %w", err)
```

File: server/server_test.go [hunk 19]
```diff
@@ -176,58 +133,47 @@ func TestServerRPCPrefix(t *testing.T) {
...
-		{
-			httpPrefix: "/testprefix", wsPrefix: "/testprefix",
-			wantHTTP:   []string{"/testprefix", "/testprefix?p=1", "/testprefix/x", "/testprefix/x?p=1"},
-			wantNoHTTP: []string{"/", "/?p=1", "/test", "/test?p=1"},
-			wantWS:     []string{"/testprefix", "/testprefix?p=1", "/testprefix/x", "/testprefix/x?p=1"},
-			wantNoWS:   []string{"/", "/?p=1", "/test", "/test?p=1"},
+			wantNoWS:   []string{"/test", "/test?p=1", "/test/x", "/test/x?p=1"},
 		},
+		/*
+			// TODO: Implement support for path prefixes.
```
Comment (kostko) [inline server/server_test.go]: What's the plan with these?

File: storage/psql/psql.go [hunk 20]
```diff
@@ -71,21 +70,36 @@ func (db *PostDb) GetTransaction(hash string) (*model.Transaction, error) {
...
-	//		b += ","
-	//	}
-	//	b += string(f.Column)
-	//}
-	//_, err := db.Db.Model(value).
-	//	OnConflict(fmt.Sprintf("(%s) DO UPDATE", b)).
-	//	Insert()
-
-	query := db.Db.Model(value).WherePK()
+	// pks := db.Db.Model(value).Table().TableModel().Table().PKs
```
Comment (kostko) [inline storage/psql/psql.go]: What's up with this commented out code? Should it just be removed?

File: storage/psql/psql_test.go [hunk 21]
```diff
@@ -11,28 +12,53 @@ import (
...
-func TestInitPostDb(t *testing.T) {
-	require := require.New(t)
-	cfg := conf.InitConfig("../../conf/server.yml")
-	db, err := InitDb(cfg.Database)
+var db *PostDB
+
+func TestMain(m *testing.M) {
+	cfg, err := conf.InitConfig("../../conf/server.yml")
 	if err != nil {
+		log.Fatal("initialize config error:", err)
```
Comment (kostko) [inline storage/psql/psql_test.go]:
```suggestion
		log.Fatal("failed to initialize config:", err)
```

File: storage/psql/psql_test.go [hunk 22]
```diff
@@ -11,28 +12,53 @@ import (
...
+	}
+	db, err = InitDB(cfg.Database)
+	if err != nil {
+		log.Println("It seems database failed to initialize. Do you have PostgreSQL running? If you have docker installed, you can try\ndocker run  -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres  -p 5432:5432 -d postgres")
```
Comment (kostko) [inline storage/psql/psql_test.go]: Break this into multiple lines instead of inserting `\n`s into a long string.

File: storage/psql/psql_test.go [hunk 23]
```diff
@@ -11,28 +12,53 @@ import (
...
 		log.Fatal("initialize db error:", err)
```
Comment (kostko) [inline storage/psql/psql_test.go]:
```suggestion
		log.Fatal("failed to initialize database:", err)
```

File: storage/psql/psql_test.go [hunk 24]
```diff
@@ -165,17 +201,21 @@ func TestUpdate(t *testing.T) {
 
 func TestDelete(t *testing.T) {
 	require := require.New(t)
-	cfg := conf.InitConfig("../../conf/server.yml")
-	db, err := InitDb(cfg.Database)
-	require.NoError(err, "initialize db")
+
+	cfg, err := conf.InitConfig("../../conf/server.yml")
```
Comment (kostko) [inline storage/psql/psql_test.go]: Can you move the path to the config file into a constant? Also it would make sense to use a separate config explicitly used for tests.

File: tests/rpc/rpc_test.go [hunk 25]
```diff
@@ -16,27 +16,14 @@ import (
...
-const (
-	// dave address generated from github.com/oasisprotocol/oasis-sdk/client-sdk/go/testing
-	daveEVMAddr = "0xdce075e1c39b1ae0b75d554558b6451a226ffe00"
-	// Zero hex bytes used in jsonrpc
-	zeroString = "0x0"
-)
-
-// The dave private key derive from the seed "oasis-runtime-sdk/test-keys: dave"
+// The dave private key derive from the seed "oasis-runtime-sdk/test-keys: dave".
+// TODO: Can we use Oasis Alice.Signer.ContextSign() directly?
```
Comment (kostko) [inline tests/rpc/rpc_test.go]: For signing Ethereum transactions? No.

File: tests/rpc/utils.go [hunk 26]
```diff
@@ -37,7 +59,233 @@ type Response struct {
...
+	w3.RegisterAPIs(rpc.GetRPCAPIs(context.Background(), rc, backend, Cfg.Gateway))
+
+	if err = w3.Start(); err != nil {
+		w3.Close()
+		return fmt.Errorf("setup: failed to start server: %v", err)
+	}
+	return nil
+}
+
+func sigspecForSigner(signer signature.Signer) types.SignatureAddressSpec {
```
Comment (kostko) [inline tests/rpc/utils.go]: I don't think you need support for general signers here as I assume you are using a specific signer?

File: model/init.go (hunk 13 above)
Comment (matevz) [reply model/init.go]: Refactored.

File: storage/psql/psql_test.go (hunk 24 above)
Comment (matevz) [reply storage/psql/psql_test.go]: Refactored.

File: server/server_test.go (hunk 19 above)
Comment (matevz) [reply server/server_test.go]: implemented.

File: indexer/utils.go [hunk 27]
```diff
@@ -206,7 +207,7 @@ func (p *psqlBackend) StoreBlockData(oasisBlock *block.Block, txResults []*clien
 		ethTx := &ethtypes.Transaction{}
 		err := rlp.DecodeBytes(rawEthTx, ethTx)
 		if err != nil {
-			p.logger.Error("Failed to decode UnverifiedTransaction", "height", blockNum, "index", txIndex, "error", err.Error())
+			p.logger.Error("Failed to decode UnverifiedTransaction", "height", blockNum, "index", txIndex, "err", err.Error())
```
Comment (ptrus) [inline indexer/utils.go]: If we are making this consistent, let's also use `"err", err` in all places (instead of `"err", err.Error()`)

File: indexer/utils.go [hunk 28]
```diff
@@ -2,9 +2,10 @@ package indexer
 
 import (
 	"encoding/hex"
-	"github.com/fxamacker/cbor/v2"
 	"math/big"
 
+	"github.com/fxamacker/cbor/v2"
+
```
Comment (ptrus) [inline indexer/utils.go]: Remove newline (so this is grouped together with other 3rd party dependencies)

File: main.go [hunk 29]
```diff
@@ -11,6 +11,7 @@ import (
 	cmnGrpc "github.com/oasisprotocol/oasis-core/go/common/grpc"
 	"github.com/oasisprotocol/oasis-core/go/common/logging"
 	"github.com/spf13/cobra"
+	"github.com/starfishlabs/oasis-evm-web3-gateway/log"
```
Comment (ptrus) [inline main.go]: Move below in the `starfishlabs` group. 

Can we add this to the `golangci-lint` config, so that this is checked by the linter:
```
linters-settings:
  goimports:
    # Put local imports after 3rd-party packages.
    local-prefixes: github.com/starfishlabs/oasis-evm-web3-gateway
```

See for example: https://github.com/oasisprotocol/oasis-core/blob/2a198f7a419391243c74f67eeb424ef6b4762903/go/.golangci.yml#L2-L4

File: tests/rpc/utils.go [hunk 30]
```diff
@@ -134,15 +345,15 @@ func CallWithError(method string, params interface{}) (*Response, error) {
 	return rpcRes, nil
 }
 
-// turns a 0x prefixed hex string to a big.Int
+// turns a 0x prefixed hex string to a big.Int.
```
Comment (ptrus) [inline tests/rpc/utils.go]:
```suggestion
/// HexToBigInt truns a 0x prefixed hex string to a big.Int
```

File: tests/rpc/utils.go [hunk 31]
```diff
@@ -37,7 +57,192 @@ type Response struct {
...
+	if err = waitForDepositEvent(acCh, oasisTesting.Alice.Address, nonce, oasisTesting.Dave.Address, ba); err != nil {
+		return fmt.Errorf("ensuring alice deposit runtime event: %w", err)
+	}
+
+	fmt.Printf("Successfully deposited %d tokens from %s to %s (eth address %x)\n", amount, oasisTesting.Alice.Address, to, oasisTesting.Dave.EthAddress)
+
+	return nil
+}
+
+// Shutdown stops web3 gateway.
```
Comment (ptrus) [inline tests/rpc/utils.go:237]:
```suggestion
/// Shutdown stops web3 gateway.
```

File: tests/rpc/utils.go [hunk 32]
```diff
@@ -37,7 +57,192 @@ type Response struct {
...
 
-var HOST = os.Getenv("HOST")
+const OasisBlockTimeout = 35 * time.Second
+
+var (
+	db *psql.PostDB
+	w3 *server.Web3Gateway
+)
+
+// Setup spins up web3 gateway.
```
Comment (ptrus) [inline tests/rpc/utils.go:66]:
```suggestion
/// Setup spins up web3 gateway.
```

**Review by ptrus — APPROVED** [review]
Thanks! This will help a lot in ensuring future changes don't break things :-)

Left some minor comments.

File: tests/rpc/utils.go (hunk 32 above)
Comment (kostko) [reply tests/rpc/utils.go:66]: Why (also below)? Go doesn't really have triple slashes for doc comments.

**Review by kostko — APPROVED** [review]

File: main.go (hunk 29 above)
Comment (matevz) [reply main.go]: good idea yeah

File: tests/rpc/utils.go (hunk 30 above)
Comment (matevz) [reply tests/rpc/utils.go]: To much rust? :wink:  It's just double `//`.

Comment (ptrus) [reply tests/rpc/utils.go]: Oh right, brainfart :grinning:
