### PR TITLE
rpc/eth/api: logging consistency

### LINKED ISSUE #62: Lessen log level of certain events
Currently, a lot of things are logged at level `error` when in fact the gateway is operating normally.

For example, querying the gateway for an inexistent block should not result in logging messages of level `error`:
```json
{
  "caller": "grpc.go:242",
  "err": "roothash: block not found",
  "level": "error",
  "method": "/oasis-core.RuntimeClient/GetBlock",
  "module": "grpc/client",
  "msg": "request failed",
  "req_seq": 90547,
  "rsp": {
    "header": {
      "version": 0,
      "namespace": "0000000000000000000000000000000000000000000000000000000000000000",
      "round": 0,
      "timestamp": "1970-01-01T00:00:00Z",
      "header_type": 0,
      "previous_hash": "0000000000000000000000000000000000000000000000000000000000000000",
      "io_root": "0000000000000000000000000000000000000000000000000000000000000000",
      "state_root": "0000000000000000000000000000000000000000000000000000000000000000",
      "messages_hash": "0000000000000000000000000000000000000000000000000000000000000000",
      "storage_signatures": null
    }
  },
  "ts": "2021-11-12T00:49:44.08224517Z"
}
{
  "caller": "api.go:183",
  "error": "roothash: block not found",
  "level": "error",
  "module": "eth_rpc",
  "msg": "GetBlock failed",
  "number": "0x1d4c00",
  "ts": "2021-11-12T00:49:44.082358214Z"
}
```
Since this is part of normal operation, it should probably be just logged at level `debug` when a developer/sysadmin want to see all the failing queries.

### LINKED ISSUE #107: Dont return internal errors in gateway responses
This was once fixed but is back again
https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/39fbf6f637de088fb9da4f69a9b5edbcd263a5c0/rpc/eth/api.go#L39-L42

`ErrBlockNotFound` & `ErrTransactionNotFound` are unused, and instead `pg: no rows in result set` is returned. 

Should be fixed and also add a test for it.

### PR DESCRIPTION
**Pull request by ptrus**
Makes logging more consistent.

Fixes:
- don't return internal storage errors in api responses: https://github.com/starfishlabs/oasis-evm-web3-gateway/issues/107
- leasen log error for "expected" (user triggered) errors to `debug` https://github.com/starfishlabs/oasis-evm-web3-gateway/issues/62
- don't return error if querying nonexistent block, transaction

### CODE REVIEW

File: rpc/eth/api.go [hunk 1]
```diff
@@ -121,44 +133,44 @@ func (api *PublicAPI) roundParamFromBlockNum(blockNum ethrpc.BlockNumber) (uint6
 
 // GetBlockByNumber returns the block identified by number.
 func (api *PublicAPI) GetBlockByNumber(blockNum ethrpc.BlockNumber, fullTx bool) (map[string]interface{}, error) {
-	api.Logger.Debug("eth_getBlockByNumber", "number", blockNum)
+	logger := api.Logger.With("method", "eth_getBlockByNumber", "block_number", blockNum, "fullTx", fullTx)
```
Comment (kostko) [inline rpc/eth/api.go]:
```suggestion
	logger := api.Logger.With("method", "eth_getBlockByNumber", "block_number", blockNum, "full_tx", fullTx)
```

**Review by kostko — APPROVED** [review]
