### PR TITLE
fix issue131

### LINKED ISSUE #131: `getBlock`: `extraData` should return `"0x" instead of `""`
Apparently this is what is expected in the response. (todo: confirm other gateways, e.g. infura)

### PR DESCRIPTION
**Pull request by anonymousGiga**
fix #131

### CODE REVIEW

File: rpc/utils/utils.go [hunk 1]
```diff
@@ -107,6 +107,10 @@ func ConvertToEthBlock(block *model.Block, fullTx bool) map[string]interface{} {
 		"totalDifficulty":  (*hexutil.Big)(big.NewInt(0)),
 	}
 
+	if len(header.Extra) == 0 {
```
Comment (ptrus) [inline rpc/utils/utils.go:110]: Nice, can you also add a simple test case for this?

Comment (anonymousGiga) [reply rpc/utils/utils.go:110]: Done.

Comment (ptrus) [reply rpc/utils/utils.go:110]: Thanks!

**Review by ptrus — APPROVED** [review]
