### PR TITLE
fix: decode both legacy and EIP-2718 transactions

### LINKED ISSUE #548: Failure to decode EIP-2718 (type2) = 'malformed transaction'
RPC Request:
```python
{'method': 'eth_sendRawTransaction', 'params': ['0x02f8ca825afe028080830186a094334d218c9afc3e4b0b7758e081eb9e49814b3f1780b86405be9a12000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000076e6f6e616d653300000000000000000000000000000000000000000000000000c080a068bfcec2d9cb07c48c97ab52bbd619949fe5bb55990ba4b9893ed47d5802b138a0725239d9c751378a976be2f2d7f49df2d8cd45e133d9ea94a127b15a3d3ac99e'], 'id': 48, 'jsonrpc': '2.0'}
```

RPC Response:
```python
{'jsonrpc': '2.0', 'id': 48, 'error': {'code': -32000, 'message': 'malformed transaction'}}
```

The responsible code in web3 gateway is:
https://github.com/oasisprotocol/oasis-web3-gateway/blob/9fb1511fac010ecb06967295495e75c3598cfabd/rpc/eth/api.go#L417-L426

The error shown in debug web3 gateway debug logs is:
```json
{"caller":"api.go:419","level":"debug","method":"eth_sendRawTransaction","module":"eth_rpc","msg":"request","ts":"2024-03-29T12:58:41.791977407Z","tx":"0x02f8ca825afe028080830186a094334d218c9afc3e4b0b7758e081eb9e49814b3f1780b86405be9a12000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000076e6f6e616d653300000000000000000000000000000000000000000000000000c080a068bfcec2d9cb07c48c97ab52bbd619949fe5bb55990ba4b9893ed47d5802b138a0725239d9c751378a976be2f2d7f49df2d8cd45e133d9ea94a127b15a3d3ac99e"}
{"caller":"api.go:424","err":"typed transaction too short","level":"debug","method":"eth_sendRawTransaction","module":"eth_rpc","msg":"failed to decode raw transaction data","ts":"2024-03-29T12:58:41.79205784Z"}
```

This error (`errShortTypedTx`) looks like it's thrown from either:
 * https://github.com/ethereum/go-ethereum/blob/a3829178af6cec64d6def9131b9340a3328cc4fc/core/types/transaction.go#L139
 * or https://github.com/ethereum/go-ethereum/blob/a3829178af6cec64d6def9131b9340a3328cc4fc/core/types/transaction.go#L199 

We should be using `UnmarshalBinary` instead of `rlp.DecodeBytes`, as `UnmarshalBinary` will handle EIP-7218 typed transactions correctly.

Decoding test in `modules/evm/src/raw_tx.rs` successfully decodes 
```rust
    #[test]
    fn test_decode_eip2718_type2() {
        /*
        rlp([
            chain_id,       = 0x5afe
            nonce,          = 0x02
            max_priority_fee_per_gas,
            max_fee_per_gas,
            gas_limit,      = 0x0186a0
            destination,    = 0x334d218c9afc3e4b0b7758e081eb9e49814b3f17
            amount,         =
            data,           = 0x05be9a12000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000076e6f6e616d653300000000000000000000000000000000000000000000000000
            access_list,    = []
            signature_y_parity,
            signature_r,    = 0x68bfcec2d9cb07c48c97ab52bbd619949fe5bb55990ba4b9893ed47d5802b138
            signature_s     = 0x725239d9c751378a976be2f2d7f49df2d8cd45e133d9ea94a127b15a3d3ac99e
        ])
        */
        decode_expect_call(
            "02f8ca825afe028080830186a094334d218c9afc3e4b0b7758e081eb9e49814b3f1780b86405be9a12000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000076e6f6e616d653300000000000000000000000000000000000000000000000000c080a068bfcec2d9cb07c48c97ab52bbd619949fe5bb55990ba4b9893ed47d5802b138a0725239d9c751378a976be2f2d7f49df2d8cd45e133d9ea94a127b15a3d3ac99e",
            Some(23294),
            "334d218c9afc3e4b0b7758e081eb9e49814b3f17",
            0,
            "05be9a12000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000076e6f6e616d653300000000000000000000000000000000000000000000000000",
            0x0186a0,
            0,
            "af8245553e1e3469cc35ecb10e5d47341a308a5d",
            2
        )
    }
```

### PR DESCRIPTION
**Pull request by CedarMist**
Closes: #548

TODO:
 - [x] Add better e2e tests

### CODE REVIEW

File: rpc/eth/api.go [hunk 1]
```diff
@@ -420,7 +419,7 @@ func (api *publicAPI) SendRawTransaction(ctx context.Context, data hexutil.Bytes
 
 	// Decode the Ethereum transaction.
 	ethTx := &ethtypes.Transaction{}
-	if err := rlp.DecodeBytes(data, ethTx); err != nil {
+	if err := ethTx.UnmarshalBinary(data); err != nil {
```
Comment (ptrus) [inline rpc/eth/api.go:424]: This should also be fixed in https://github.com/oasisprotocol/oasis-web3-gateway/blob/9fb1511fac010ecb06967295495e75c3598cfabd/indexer/utils.go#L253-L259

otherwise indexing will fail when such transaction is processed.

Hm we should coordinate to update all gateways quickly once we release this fix.

**Review by ptrus — APPROVED** [review]

File: tests/rpc/tx_test.go [hunk 2]
```diff
@@ -84,13 +84,39 @@ func testContractCreation(t *testing.T, value *big.Int) uint64 {
...
+	gasPrice, err := ec.SuggestGasPrice(context.Background())
+	require.Nil(t, err, "get price failed")
+	var (
+		tx *types.Transaction
+	)
+	if txEIP == 1559 {
+		tx = types.NewTx(&types.DynamicFeeTx{
+			Nonce: nonce,
+			Value: value,
+			// XXX: https://github.com/oasisprotocol/oasis-sdk/issues/1673
```
Comment (ptrus) [inline tests/rpc/tx_test.go]: Do we want to wait for https://github.com/oasisprotocol/oasis-sdk/issues/1673 to be deployed on testnet, or should w merge this and release the fixed web3 gw beforehand?

Comment (kostko) [reply tests/rpc/tx_test.go]: We can probably go ahead with this as it shouldn't break anything (except Web3 gateway deployments), such transactions will just be rejected by the runtime most of the time unless they are carefully constructed.

Comment (ptrus) [reply tests/rpc/tx_test.go]: Seems good, please rebase whenever you will have the time @CedarMist

**Comment by ptrus** [comment]
@CedarMist do we want to get this merged and deployed?

**Comment by ptrus** [comment]
I'll finish up this PR
