### PR TITLE
indexer: query max block gas limit

### LINKED ISSUE #151: Hardcoded block gas limit in block headers is incorrect
The block gas limit is hardcoded to 21,000,000 in returned block headers. This value is incorrect.

https://github.com/oasisprotocol/emerald-web3-gateway/blob/50a5aefa81c2f9f8f3e5b2c4f8e0cec98d896ea2/indexer/utils.go#L88

### PR DESCRIPTION
**Pull request by ptrus**
Fixes: https://github.com/oasisprotocol/emerald-web3-gateway/issues/151

### CODE REVIEW

File: indexer/backend.go [hunk 1]
```diff
@@ -77,6 +77,7 @@ type Backend interface {
 	Index(
 		oasisBlock *block.Block,
 		txResults []*client.TransactionWithResults,
+		maxBatchSize uint64,
```
Comment (kostko) [inline indexer/backend.go]: Why is this called `maxBatchSize`, probably better to call it `blockGasLimit`?

Comment (ptrus) [reply indexer/backend.go]: renamed

**Review by kostko — APPROVED** [review]
